name: Build and Upload Goldspace from macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add Rust target for i686
      run: rustup target add i686-unknown-linux-gnu

    - name: Set up dependencies
      run: |
        brew update
        brew install nasm mtools

    - name: Edit Makefile
      run: sed -i '' -e 's/ -g//g' -e 's/ -m elf_i386//g' Makefile

    - name: Build ISO
      run: make

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: goldspace
        path: goldspace.iso
