name: Build and Upload Goldspace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build ISO
      run: make

    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
        name: goldspace
        path: goldspace.iso
